name: 'Check, Build, Test, Publish DevContainer'
on:
  pull_request:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v3

      - name: Check, Build, Test, Publish
        uses: devcontainers/ci@v0.3
        with:
          runCmd: |
            # Check
            pre-commit run --show-diff-on-failure --color=always --all-files

            # Build
            ./scripts/build.sh s-core-devcontainer

            # Test
            ./scripts/test.sh s-core-devcontainer

            # Publish
            echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            ./scripts/publish.sh s-core-devcontainer
