name: 'Verify DevContainer'
description: 'This workflow is checking that updates to the devcontainer do not break obvious stuff. It does static analysis, building, testing.'
on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: 'Check, Build, Test, Publish DevContainer'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v3

      - name: Check, Build, Test, Publish
        uses: devcontainers/ci@v0.3
        with:
          runCmd: |
            # Check
            pre-commit run --show-diff-on-failure --color=always --all-files || exit -1

            # Build
            ./scripts/build.sh

            # Test
            ./scripts/test.sh

            # Publish a snapshot
            ## TODO: Remove this step before the first release
            echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            ./scripts/publish.sh snapshot
